### ISSUE TITLE
Energize don't buffer reactions/commands properly.

### ISSUE THREAD

**Issue by zxz41** [Energizers/Energize#14]
If the bot is being flooded with reactions (Add to queue, Play/Pause, Volume up/down) the bot chokes (Trying to edit messages too rapidly, music performance chokes, input being accepted even long after it was issued.)

The worst is when the same track is added to the queue rapidly.

<img src="https://user-images.githubusercontent.com/11709919/60735874-40389f80-9f55-11e9-9574-e83c9ca7e697.png" height="440px">

**Comment by Earu** [comment]
Fixed, follow up in: https://github.com/Energizers/Energize/issues/23
