### ISSUE TITLE
Spotify search malfunctioning on startup until Octovisor loads

### ISSUE THREAD

**Issue by TheMulti0** [Energizers/Energize#8]
Spotify search (using the `(x)spotify` command) will return no results until Octovisor will finish loading.
I heard from the owner of this repository that all commands may fail before `ShardReady` event, because Discord.NET doesn't have all the information it needs in order to execute operations.

Note: I tested it only in development, and tested only with an Octovisor configuration that makes it fail to connect (without an additional listener), I doubt it but it may work with a functioning Octovisor configuration.

**Comment by Earu** [comment]
It is likely because Discord.NET did not complete its information fetching, the `ShardReady` event is an indicator that all the necessary information has been retrieved for a shard. But it is worth investigating as this could be a problem during a restart.
